// This file is automatically generated. Do not modify it manually.
// You can publish and connect your app to a new Firebase project by running
// `npx firebase-frameworks-tools select-project`

import { FirebaseOptions, initializeApp } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: "placeholder-api-key",
  authDomain: "placeholder-auth-domain",
  projectId: "ikm-marketplace-a4a3a",
  storageBucket: "placeholder-storage-bucket",
  messagingSenderId: "placeholder-messaging-sender-id",
  appId: "placeholder-app-id",
};

export const app = initializeApp(firebaseConfig);
