// This file is automatically generated. Do not modify it manually.
// You can publish and connect your app to a new Firebase project by running
// `npx firebase-frameworks-tools select-project`

import { FirebaseOptions, initializeApp } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyABk4yPJsRKWpTT0xheXTsi8Cw0s4BPuiE",
  authDomain: "ikm-marketplace.firebaseapp.com",
  projectId: "ikm-marketplace",
  storageBucket: "ikm-marketplace.appspot.com",
  messagingSenderId: "723822682554",
  appId: "1:723822682554:web:188fa4303a8b3f8737bd83"
};

export const app = initializeApp(firebaseConfig);
