// This file is automatically generated. Do not modify it manually.
// You can publish and connect your app to a new Firebase project by running
// `npx firebase-frameworks-tools select-project`

'use client';

import { app } from '@/firebase/config';
import { Auth, getAuth, connectAuthEmulator } from 'firebase/auth';
import {
  Firestore,
  getFirestore,
  connectFirestoreEmulator,
} from 'firebase/firestore';
import { getStorage, connectStorageEmulator } from 'firebase/storage';
import {
  isSupported,
  getAnalytics,
  initializeAnalytics,
} from 'firebase/analytics';

export * from './provider';

let auth: Auth;
let firestore: Firestore;

function initialize(): void {
  auth = getAuth(app);
  firestore = getFirestore(app);
}

initialize();

export function getFirebaseAuth() {
  return auth;
}

export function getFirestoreInstance() {
  return firestore;
}
