
// This file is automatically generated. Do not modify it manually.
// You can publish and connect your app to a new Firebase project by running
// `npx firebase-frameworks-tools select-project`

'use client';

import React, { createContext, useContext } from 'react';
import { Auth } from 'firebase/auth';
import { Firestore } from 'firebase/firestore';

import { getFirebaseAuth, getFirestoreInstance } from '@/firebase';

const FirebaseContext = createContext<{
  auth: Auth;
  firestore: Firestore;
} | null>(null);

export function FirebaseProvider({ children }: { children: React.ReactNode }) {
  const auth = getFirebaseAuth();
  const firestore = getFirestoreInstance();

  return (
    <FirebaseContext.Provider value={{ auth, firestore }}>
      {children}
    </FirebaseContext.Provider>
  );
}

export const useFirebase = () => {
  const context = useContext(FirebaseContext);
  if (context === null) {
    throw new Error('useFirebase must be used within a FirebaseProvider');
  }
  return context;
};
