// This file is automatically generated. Do not modify it manually.
// You can publish and connect your app to a new Firebase project by running
// `npx firebase-frameworks-tools select-project`

'use client';

import React, { createContext, useContext } from 'react';
import { Auth } from 'firebase/auth';
import { Firestore } from 'firebase/firestore';
import { FirebaseStorage } from 'firebase/storage';
import { app } from './config'; // Import the initialized app

const FirebaseContext = createContext<{
  auth: Auth;
  firestore: Firestore;
  storage: FirebaseStorage;
} | null>(null);

export function FirebaseProvider({ 
    children, 
    auth, 
    firestore,
    storage 
}: { 
    children: React.ReactNode, 
    auth: Auth, 
    firestore: Firestore,
    storage: FirebaseStorage 
}) {
  
  return (
    <FirebaseContext.Provider value={{ auth, firestore, storage }}>
      {children}
    </FirebaseContext.Provider>
  );
}

export const useFirebase = () => {
  const context = useContext(FirebaseContext);
  if (context === null) {
    throw new Error('useFirebase must be used within a FirebaseProvider');
  }
  return context;
};
